import { cache } from "react"
import type { Neighborhood, Property } from "@/lib/properties/types"

export const mockNeighborhoods: Neighborhood[] = [
  { name: "Plano Piloto", slug: "plano-piloto", count: 312, description: "RA I · Centro histórico e político", featured: true },
  { name: "Gama", slug: "gama", count: 98, description: "RA II · Cidade satélite consolidada" },
  { name: "Taguatinga", slug: "taguatinga", count: 187, description: "RA III · Polo comercial do DF" },
  { name: "Brazlândia", slug: "brazlandia", count: 34, description: "RA IV · Rural e tranquilo" },
  { name: "Sobradinho", slug: "sobradinho", count: 76, description: "RA V · Bairro tradicional ao norte" },
  { name: "Planaltina", slug: "planaltina", count: 52, description: "RA VI · Uma das cidades mais antigas do DF" },
  { name: "Paranoá", slug: "paranoa", count: 41, description: "RA VII · Às margens do Lago Paranoá" },
  { name: "Núcleo Bandeirante", slug: "nucleo-bandeirante", count: 29, description: "RA VIII · Primeira cidade do DF" },
  { name: "Ceilândia", slug: "ceilandia", count: 143, description: "RA IX · Maior região administrativa do DF" },
  { name: "Guará", slug: "guara", count: 88, description: "RA X · Bem localizado e planejado" },
  { name: "Cruzeiro", slug: "cruzeiro", count: 57, description: "RA XI · Residencial próximo ao Plano Piloto" },
  { name: "Samambaia", slug: "samambaia", count: 119, description: "RA XII · Crescimento acelerado" },
  { name: "Santa Maria", slug: "santa-maria", count: 67, description: "RA XIII · Sul do DF em expansão" },
  { name: "São Sebastião", slug: "sao-sebastiao", count: 48, description: "RA XIV · Leste do DF, em crescimento" },
  { name: "Recanto das Emas", slug: "recanto-das-emas", count: 61, description: "RA XV · Comunidade ativa e diversa" },
  { name: "Lago Sul", slug: "lago-sul", count: 38, description: "RA XVI · Luxuoso e tranquilo", featured: true },
  { name: "Riacho Fundo", slug: "riacho-fundo", count: 22, description: "RA XVII · Residencial e familiar" },
  { name: "Lago Norte", slug: "lago-norte", count: 44, description: "RA XVIII · Alto padrão à beira do lago", featured: true },
  { name: "Candangolândia", slug: "candangolandia", count: 18, description: "RA XIX · Pequena e histórica" },
  { name: "Águas Claras", slug: "aguas-claras", count: 156, description: "RA XX · Moderna e em expansão", featured: true },
  { name: "Riacho Fundo II", slug: "riacho-fundo-ii", count: 19, description: "RA XXI · Residencial planejado" },
  { name: "Sudoeste/Octogonal", slug: "sudoeste-octogonal", count: 64, description: "RA XXII · Planejado e valorizado", featured: true },
  { name: "Varjão", slug: "varjao", count: 11, description: "RA XXIII · Comunidade entre o lago e a cidade" },
  { name: "Park Way", slug: "park-way", count: 27, description: "RA XXIV · Chácaras e alto padrão", featured: true },
  { name: "SCIA/Estrutural", slug: "scia-estrutural", count: 9, description: "RA XXV · Área de desenvolvimento" },
  { name: "Sobradinho II", slug: "sobradinho-ii", count: 53, description: "RA XXVI · Expansão de Sobradinho" },
  { name: "Jardim Botânico", slug: "jardim-botanico", count: 31, description: "RA XXVII · Condomínios e natureza" },
  { name: "Itapoã", slug: "itapoa", count: 36, description: "RA XXVIII · Bairro em valorização" },
  { name: "SIA", slug: "sia", count: 7, description: "RA XXIX · Setor industrial e comercial" },
  { name: "Vicente Pires", slug: "vicente-pires", count: 72, description: "RA XXX · Condomínios e praticidade" },
  { name: "Fercal", slug: "fercal", count: 8, description: "RA XXXI · Norte do DF, área rural" },
  { name: "Sol Nascente e Pôr do Sol", slug: "sol-nascente-por-do-sol", count: 45, description: "RA XXXII · Grande e populoso" },
  { name: "Arniqueira", slug: "arniqueira", count: 39, description: "RA XXXIII · Entre Águas Claras e Taguatinga" },
  { name: "Arapoanga", slug: "arapoanga", count: 16, description: "RA XXXIV · Expansão de Planaltina" },
  { name: "Água Quente", slug: "agua-quente", count: 12, description: "RA XXXV · Região em desenvolvimento" },
]

export const mockProperties: Property[] = [
  {
    id: "1",
    code: "PU-0001",
    slug: "apartamento-asa-sul-sqn-308",
    title: "Apartamento 4 quartos com vista para o Parque da Cidade",
    type: "apartamento",
    transactionType: "venda",
    price: 1850000,
    condoFee: 1800,
    iptu: 650,
    city: "Brasília",
    neighborhood: "Plano Piloto",
    address: "SQS 308, Bloco A",
    privateArea: 180,
    totalArea: 210,
    bedrooms: 4,
    suites: 2,
    bathrooms: 3,
    parkingSpaces: 2,
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
    featured: true,
    acceptsPets: true,
    solarOrientation: "Nascente",
  },
  {
    id: "2",
    code: "PU-0002",
    slug: "cobertura-noroeste-sqnw-111",
    title: "Cobertura duplex com terraço gourmet no Noroeste",
    type: "cobertura",
    transactionType: "venda",
    price: 3200000,
    condoFee: 2500,
    iptu: 1200,
    city: "Brasília",
    neighborhood: "Plano Piloto",
    address: "SQNW 111, Bloco B",
    privateArea: 320,
    totalArea: 380,
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    parkingSpaces: 4,
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80"],
    featured: true,
    acceptsPets: true,
    solarOrientation: "Poente",
  },
  {
    id: "3",
    code: "PU-0003",
    slug: "apartamento-aguas-claras-rua-37",
    title: "Apartamento moderno 3 quartos em Águas Claras",
    type: "apartamento",
    transactionType: "aluguel",
    price: 4500,
    condoFee: 800,
    iptu: 200,
    city: "Brasília",
    neighborhood: "Águas Claras",
    address: "Rua 37 Norte, Lote 12",
    privateArea: 95,
    totalArea: 110,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpaces: 2,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"],
    featured: false,
    acceptsPets: true,
    solarOrientation: "Nascente",
  },
  {
    id: "4",
    code: "PU-0004",
    slug: "casa-lago-sul-shis-qi-25",
    title: "Casa de alto padrão com piscina no Lago Sul",
    type: "casa",
    transactionType: "venda",
    price: 8500000,
    condoFee: 0,
    iptu: 3500,
    city: "Brasília",
    neighborhood: "Lago Sul",
    address: "SHIS QI 25, Conjunto 8",
    privateArea: 550,
    totalArea: 1200,
    bedrooms: 5,
    suites: 5,
    bathrooms: 7,
    parkingSpaces: 6,
    images: ["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80"],
    featured: true,
    acceptsPets: true,
    solarOrientation: "Norte/Sul",
  },
  {
    id: "5",
    code: "PU-0005",
    slug: "apartamento-sudoeste-sqsw-300",
    title: "Apartamento reformado 2 quartos no Sudoeste",
    type: "apartamento",
    transactionType: "aluguel",
    price: 3800,
    condoFee: 950,
    iptu: 280,
    city: "Brasília",
    neighborhood: "Sudoeste/Octogonal",
    address: "SQSW 300, Bloco C",
    privateArea: 75,
    totalArea: 85,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpaces: 1,
    images: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80"],
    featured: false,
    acceptsPets: false,
    solarOrientation: "Poente",
  },
  {
    id: "6",
    code: "PU-0006",
    slug: "apartamento-asa-norte-sqs-405",
    title: "Apartamento amplo 3 quartos próximo ao Parque Olhos D'água",
    type: "apartamento",
    transactionType: "venda",
    price: 1450000,
    condoFee: 1400,
    iptu: 520,
    city: "Brasília",
    neighborhood: "Plano Piloto",
    address: "SQN 405, Bloco D",
    privateArea: 140,
    totalArea: 165,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpaces: 2,
    images: ["https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&q=80"],
    featured: false,
    acceptsPets: true,
    solarOrientation: "Nascente",
  },
  {
    id: "7",
    code: "PU-0007",
    slug: "casa-lago-norte-sqln-314",
    title: "Casa moderna 4 quartos à beira do Lago Norte",
    type: "casa",
    transactionType: "venda",
    price: 4200000,
    condoFee: 0,
    iptu: 1800,
    city: "Brasília",
    neighborhood: "Lago Norte",
    address: "SQLN 314, Conjunto 6",
    privateArea: 420,
    totalArea: 680,
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    parkingSpaces: 4,
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80"],
    featured: true,
    acceptsPets: true,
    solarOrientation: "Norte/Sul",
  },
  {
    id: "8",
    code: "PU-0008",
    slug: "chacara-park-way-conjunto-3",
    title: "Chácara com piscina e área gourmet no Park Way",
    type: "casa",
    transactionType: "venda",
    price: 6500000,
    condoFee: 0,
    iptu: 2800,
    city: "Brasília",
    neighborhood: "Park Way",
    address: "SMPW Quadra 3, Conjunto 5",
    privateArea: 800,
    totalArea: 5000,
    bedrooms: 5,
    suites: 5,
    bathrooms: 6,
    parkingSpaces: 8,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80"],
    featured: false,
    acceptsPets: true,
    solarOrientation: "Norte/Sul",
  },
  {
    id: "9",
    code: "PU-0009",
    slug: "apartamento-taguatinga-cnh-1",
    title: "Apartamento reformado 3 quartos em Taguatinga Norte",
    type: "apartamento",
    transactionType: "venda",
    price: 850000,
    condoFee: 600,
    iptu: 280,
    city: "Brasília",
    neighborhood: "Taguatinga",
    address: "CNH 1, Bloco B",
    privateArea: 90,
    totalArea: 105,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpaces: 2,
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80"],
    featured: false,
    acceptsPets: false,
    solarOrientation: "Nascente",
  },
  {
    id: "10",
    code: "PU-0010",
    slug: "apartamento-guara-qe-22",
    title: "Apartamento 2 quartos no Guará II",
    type: "apartamento",
    transactionType: "aluguel",
    price: 3200,
    condoFee: 750,
    iptu: 180,
    city: "Brasília",
    neighborhood: "Guará",
    address: "QE 22, Bloco D",
    privateArea: 70,
    totalArea: 80,
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    parkingSpaces: 1,
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"],
    featured: false,
    acceptsPets: true,
    solarOrientation: "Poente",
  },
  {
    id: "11",
    code: "PU-0011",
    slug: "casa-vicente-pires-condominio-villa",
    title: "Casa em condomínio fechado 3 quartos em Vicente Pires",
    type: "casa",
    transactionType: "venda",
    price: 1100000,
    condoFee: 900,
    iptu: 380,
    city: "Brasília",
    neighborhood: "Vicente Pires",
    address: "Trecho 2, Conjunto 5",
    privateArea: 160,
    totalArea: 300,
    bedrooms: 3,
    suites: 2,
    bathrooms: 3,
    parkingSpaces: 2,
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80"],
    featured: false,
    acceptsPets: true,
    solarOrientation: "Nascente",
  },
  {
    id: "12",
    code: "PU-0012",
    slug: "casa-jardim-botanico-condominio-real",
    title: "Casa com jardim e área verde no Jardim Botânico",
    type: "casa",
    transactionType: "aluguel",
    price: 7500,
    condoFee: 1200,
    iptu: 420,
    city: "Brasília",
    neighborhood: "Jardim Botânico",
    address: "SHJE Área Especial, Conjunto 3",
    privateArea: 240,
    totalArea: 600,
    bedrooms: 4,
    suites: 2,
    bathrooms: 4,
    parkingSpaces: 3,
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80"],
    featured: false,
    acceptsPets: true,
    solarOrientation: "Norte/Sul",
  },
]

export const mockNeighborhoodsWithCount: Neighborhood[] = mockNeighborhoods.map((n) => ({
  ...n,
  count: mockProperties.filter((p) => p.neighborhood === n.name).length || n.count,
}))

export const getFeaturedProperties = () => mockProperties.filter((p) => p.featured)
export const getPropertyBySlug = cache((slug: string) => mockProperties.find((p) => p.slug === slug))
export const getNeighborhoodBySlug = (slug: string) => mockNeighborhoods.find((n) => n.slug === slug)
export const getPropertiesByNeighborhood = (name: string) =>
  mockProperties.filter((p) => p.neighborhood === name)
